### ISSUE TITLE
How to play initialize.ck

### ISSUE THREAD

**Issue by bas080** [CorcovadoMing/ChucKProject#1]
When I do chuck initialize.ck i get this error.

[initialize.ck]:line(1): class 'Shred' has no member 'dir'

How should I play the file?

**Comment by CorcovadoMing** [comment]
which version of chuck did you use?
I've test all the files on chuck 1.3.3.0 without problems

**Comment by bas080** [comment]
1.2.0.8, The one that comes by default in the ubuntu repository. I will try to update and play it again. Thnx for letting me know my stuff is outdated.

**Comment by CorcovadoMing** [comment]
http://chuck.cs.princeton.edu/release/VERSIONS
please check about this
the directory I/O function was added from 1.3.2.0 

you could update your chuck from http://chuck.cs.princeton.edu
:)
